name: simple_apple_widget
description: "Demonstrates how to use home_widget plugin on apple devices (mac + ios)"

publish_to: 'none' 

version: 0.1.0

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
    
  home_widget:
    path: ../../packages/home_widget

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
